### ISSUE TITLE
cilium挂载目录找不到cni

### ISSUE THREAD

**Issue by zhuchance** [easzlab/kubeasz#1033]
### bug 复现：
> 现象创建pod的时候pod一直在等待describe信息如下：
Warning  FailedCreatePodSandBox  <invalid> (x7645 over 19h)  kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "马赛克": failed to find plugin "cilium-cni" in path [/opt/kube/bin]
### 解决方法：
kubectl 里面--cni-bin-dir参数 和cilium yaml文件路径不一致
```yaml
# To install cilium cni plugin in the host
      - hostPath:
          path:  /opt/cni/bin
          type: DirectoryOrCreate
        name: cni-path
```
