### ISSUE TITLE
traefix 版本跟k8s版本不匹配，导致安装报错

### ISSUE THREAD

**Issue by kenwoodjw** [easzlab/kubeasz#1077]
### 问题描述
k8s 1.22版本在执行easyctl setup k8-01 07 安装cluster-addon 插件 报错
![a2a9c32454718670c09978bd7a230b1](https://user-images.githubusercontent.com/10386710/136668427-2d52443c-0fc2-472d-ab93-46738545edc0.png)
### 问题分析
traefik ingresroute yaml的apiversion在k8s 1.22之后废弃为v1版本
[k8s官方文档说明](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122)
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us
spec:
  group: traefik.containo.us
  version: v1alpha1
  names:
    kind: IngressRoute
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced
```
traefik在v2.5版本修复以上问题
https://github.com/traefik/traefik/pull/7815
https://github.com/traefik/traefik/releases/tag/v2.5.0
### 解决方法
1. 更新https://github.com/easzlab/kubeasz/tree/3.1.1/roles/cluster-addon/files traefik文件为https://github.com/traefik/traefik-helm-chart/releases/tag/v10.3.0 的版本
