### ISSUE TITLE
Prometheus-Operator监控kube-controller-manager失败

### ISSUE THREAD

**Issue by comeonyang43** [easzlab/kubeasz#1097]
1）问题描述：k8s版本1.22.4，kube-controller-manager监听端口10257.监控Target页面显示DOWN,错误提示server returned HTTP status 403 Forbidden.点击metrics url 提示：
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}

2）prometheus values文件相关部分配置：
kubeControllerManager:
  enabled: true
  endpoints:
  - 192.168.20.128
  service:
    enabled: true
    port: 10257
    targetPort: 10257
 serviceMonitor:
    enabled: true
    https: true
    insecureSkipVerify: true

**Comment by tanmx** [comment]
同样的问题  kube-scheduler 的 10259 端口也是一样的问题 
```
kubeScheduler:
  enabled: true
  ## If your kube scheduler is not deployed as a pod, specify IPs it can be found on
  ##
  endpoints:
{% for h in groups['kube_master'] %}
    - {{ hostvars[h]['ansible_ssh_host'] }}
{% endfor %}
  service:
    enabled: true
    port: 10259
    targetPort: 10259
  serviceMonitor:
    https: true
    insecureSkipVerify: true
```
