### ISSUE TITLE
traefik ingress-controller怎么部署https

### ISSUE THREAD

**Issue by hanfuyou88** [easzlab/kubeasz#309]
部署的web应用需要https访问，测试的时候如果不加证书配置访问23456端口正常，证书导入后把证书加上如下例子：
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: https-test
spec:
  tls:
  - hosts:
    - www.yy.com
    secretName: ingress-https
  rules:
  - host: www.yy.com
    http:
      paths:
      - backend:
           serviceName: nginx
           servicePort: 80
再用https:www.yy.com测试访问不了，怎么更改可以用https访问。

**Comment by gjmzj** [comment]
这个有官方文档 https://docs.traefik.io/user-guide/kubernetes/#add-a-tls-certificate-to-the-ingress
例子中是这样的：
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: traefik-ui.minikube
    http:
      paths:
      - backend:
          serviceName: traefik-web-ui
          servicePort: 80
  tls:
   - secretName: traefik-ui-tls-cert
```
