### ISSUE TITLE
升级calico 3.3

### ISSUE THREAD

**Issue by sunshanpeng** [easzlab/kubeasz#413]
目前calico已经出到3.4了，请问群主有升级的打算吗？或者说已安装的calico怎么样升级到3.3+，求指教

**Comment by gjmzj** [comment]
calico 目前项目使用3.2.4，比较稳定，且已经支持ipvs;
后续会跟踪更新到3.x，

**Comment by sunshanpeng** [comment]
3.3的calico-node可以直接当路由反射器rr，看起来很不错，可以跟集群外互通
<https://docs.projectcalico.org/v3.3/usage/configuration/bgp#configuring-in-cluster-route-reflectors>

**Comment by weilinqwe** [comment]
@sunshanpeng 集群外服务器如果利用集群内的rr来直接访问集群内的pod，试验过吗？是不是配置bird？

**Comment by sunshanpeng** [comment]
> @sunshanpeng 集群外服务器如果利用集群内的rr来直接访问集群内的pod，试验过吗？是不是配置bird？

抱歉，最近在忙别的事情，后面会试验一下。

**Comment by sunshanpeng** [comment]
按照群主的文档用了calico3.3.2 并开启了rr，感谢群主。
这边反馈1个问题：
开启rr后再加节点会有问题，现象是手动设置的routeReflectorClusterID配置没有了，需要重新配置 Route Reflector 节点。
```yaml
# 只需单节点执行一次
- name: 运行 calico网络
  shell: "{{ bin_dir }}/kubectl apply -f /opt/kube/kube-system/calico/ && sleep 5"
  delegate_to: "{{ groups.deploy[0] }}"
  run_once: true
```
加节点的时候这段应该不能再执行了。

另外，我们跟集群外网络还没打通，还在摸索中，不知道群主有没有试过。。。
