### ISSUE TITLE
集群外部使用traefik开放对外端口,添加访问路径问题

### ISSUE THREAD

**Issue by huanzui** [easzlab/kubeasz#579]
集群外部使用traefik开放对外端口

hosts已添加
10.3.87.35 eureka-ui.com

配置
```
- host: eureka-ui.com
    http:
      paths:
      - path: 
        backend:
          serviceName: eureka-server
          servicePort: 1025
  - host: eureka-replica-ui.com
    http:
      paths:
      - path: 
        backend:
          serviceName: eureka-server-replica
          servicePort: 1026 
```
访问 http://eureka-ui.com/  是没问题的
但这种模式
```
 - host: eureka-ui.com
    http:
      paths:
      - path:  /eureka
        backend:
          serviceName: eureka-server
          servicePort: 1025
      - path:  /eurekarep
        backend:
          serviceName: eureka-server-replica
          servicePort: 1026
```
访问 http://eureka-ui.com/eureka   报404 页面不存在，请问这个traefik配置上有问题么？

**Comment by gjmzj** [comment]
因为第二种方式，http://eureka-ui.com/eureka 是转发到实际 eureka-server服务的路径 /eureka，而不是 /

**Comment by huanzui** [comment]
> 因为第二种方式，http://eureka-ui.com/eureka 是转发到实际 eureka-server服务的路径 /eureka，而不是 /

是发现了这个问题 访问的是eureka-server服务的路径 /eureka，后来找到一个配置：
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip

```
metadata:
  name: eurekaui
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: eureka-ui.com
    http:
      paths:
      - path: /eureka
        backend:
          serviceName: joinmanage-eureka-server
          servicePort: 1025
      - path: /eureka-replica
        backend: 
          serviceName: joinmanage-eureka-server-replica
          servicePort: 1026
```

确实可以这样访问了，http://eureka-ui.com/eureka  网页数据可以取
但eureka里面的静态资源 http://monitor-ui.com/eureka/js/wro.js 报404，有点搞不懂了
