### ISSUE TITLE
创建资源对象所处namespace与资源文件yaml里指定的namespace不一致

### ISSUE THREAD

**Issue by weifan01** [easzlab/kubeasz#594]
版本 v1.13.3

根据下面的yaml资源文件创建对象，会创建在default namespace，而不是y namespace
使用kubectl create命令行创建正常
目前只有y这个namespace有这个问题，麻烦大佬给分析分析

YML内容:

```
---
apiVersion: v1
kind: Service
metadata:
  name: svc-youyou
  namespace: y
  labels:
    app: youyou
spec:
  ports:
  - port: 6000
    targetPort: 6000
    protocol: TCP
  selector:
    app: youyou
```

**Comment by weifan01** [comment]
之前在此集群中创建过y namespace，没有出现问题，后来删掉后重建的时候出问题了

**Comment by gjmzj** [comment]
可以先创建 y 命名空间
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: y

---
apiVersion: v1
kind: Service
metadata:
  name: svc-youyou
  namespace: y
  labels:
    app: youyou
spec:
  ports:
  - port: 6000
    targetPort: 6000
    protocol: TCP
  selector:
    app: youyou
```
