### ISSUE TITLE
centos7初始化导致systemd损坏

### ISSUE THREAD

**Issue by ndaysy** [easzlab/kubeasz#635]
使用最新版本离线安装，环境是centos7（非mini），系统原来自带systemd，初始化后会导致systemctl命令不可用。
估计是 ansible-playbook 01.prepare.yml 安装 basic_bionic 离线包中引起的
建议如果系统已经安装了systemd就不用重新安装了。
错误信息：
TASK [prepare : 重启rsyslog服务] *****************************************************
fatal: [192.168.184.176]: FAILED! => {"changed": false, "cmd": "/usr/bin/systemctl", "msg": "/usr/bin/systemctl: error while loading shared libraries: liblz4.so.1: cannot open shared object file: No such file or directory", "rc": 127, "stderr": "/usr/bin/**systemctl: error while loading shared libraries: liblz4.so.1: cannot open shared object file: No such file or directory**\n", "stderr_lines": ["/usr/bin/systemctl: error while loading shared libraries: liblz4.so.1: cannot open shared object file: No such file or directory"], "stdout": "", "stdout_lines": []}

**Comment by gjmzj** [comment]
basic_bionic 离线包是ubuntu1804才会安装的，centos7不可能安装这个；
离线安装只安装有限几个基础软件，像systemd这种庞然大物不可能去安装；
```
- name: 安装基础软件包
  yum: 
    name: 
      - bash-completion     # bash命令补全工具，需要重新登录服务器生效
      - conntrack-tools     # ipvs 模式需要
      - ipset               # ipvs 模式需要
      - ipvsadm             # ipvs 模式需要
      - libseccomp          # 安装containerd需要
      - nfs-utils           # 挂载nfs 共享文件需要 (创建基于 nfs的PV 需要)
      - psmisc              # 安装psmisc 才能使用命令killall，keepalive的监测脚本需要
      - rsync               # 文件同步工具，分发证书等配置文件需要
      - socat               # 用于port forwarding
    state: present
```
