### ISSUE TITLE
01-创建证书和安装准备过程没有安装kubectl客户端的步骤

### ISSUE THREAD

**Issue by Totobo** [easzlab/kubeasz#699]
release=2.0.3
一共两个问题
1.
根据[文档](https://github.com/easzlab/kubeasz/blob/master/docs/setup/01-CA_and_prerequisite.md#01-%E5%88%9B%E5%BB%BA%E8%AF%81%E4%B9%A6%E5%92%8C%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE)描述，prepare role里面执行的步骤包括kubectl客户端安装。但实际`roles/prepare/tasks/main.ym`里面并没有安装kubectl的过程；
2.
`/root/.kube/config`这个配置文件是配合kubectl使用，我理解是应该只下发到master节点，按照现在的逻辑是在prepare阶段分发到了`kube-master` `kube-node`和`etcd`的主机上。不太清楚这么做的逻辑是什么

**Comment by gjmzj** [comment]
1.kubectl只要下载二进制即可，不用安装
2.确实kubeconfig可以只下发到master节点
```
- block:
    - name: 分发证书相关
      copy: src={{ base_dir }}/.cluster/ssl/{{ item }} dest={{ ca_dir }}/{{ item }}
      with_items:
      - admin.pem
      - admin-key.pem
      - ca.pem
      - ca-key.pem
      - ca-config.json

    - name: 添加 kubectl 命令自动补全
      lineinfile:
        dest: ~/.bashrc
        state: present
        regexp: 'kubectl completion'
        line: 'source <(kubectl completion bash)'

    - name: 分发 kubeconfig配置文件
      copy: src=/root/.kube/config dest=/root/.kube/config

    - name: 分发 kube-proxy.kubeconfig配置文件
      copy: src={{ base_dir }}/.cluster/kube-proxy.kubeconfig dest=/etc/kubernetes/kube-proxy.kubeconfig
  when: "inventory_hostname in groups['kube-master'] or inventory_hostname in groups['kube-node']"
```
目前是下发到了kube-master和kube-node，可以按自己需要调整
