### ISSUE TITLE
kube-controller-manager配置项不生效

### ISSUE THREAD

**Issue by diandiankou** [easzlab/kubeasz#709]
群主好，为了hpa能快速响应， 缩短node notready重新调度时间，添加一下配置，不知道为什么一个都不生效
kubeas版本:2.0.2   k8s版本：1.14.3
kube-controller-manager配置：
vi /etc/systemd/system/kube-controller-manager.service
--horizontal-pod-autoscaler-sync-period=10s
--horizontal-pod-autoscaler-downscale-delay=30s
--horizontal-pod-autoscaler-upscale-delay=30s
--node-monitor-period=2s \
--node-monitor-grace-period=10s \
--pod-eviction-timeout=30s \

systemctl daemon-reload 
systemctl restart kube-controller-manager.service
systemctl status kube-controller-manager.service

**Comment by diandiankou** [comment]
hpa快速响应时间配置现已改为以下：
--horizontal-pod-autoscaler-cpu-initialization-period duration     Default: 5m0s
--horizontal-pod-autoscaler-downscale-stabilization duration     Default: 5m0s
--horizontal-pod-autoscaler-initial-readiness-delay duration     Default: 30s
--horizontal-pod-autoscaler-sync-period duration     Default: 15s
--horizontal-pod-autoscaler-tolerance float     Default: 0.1
node nodeready调度时间配置还是不生效。

**Comment by TophillZK** [comment]
加快node状态变更的配置需要如下操作
```
vi /etc/systemd/system/kubelet.service

  --node-status-update-frequency=4s \

systemctl daemon-reload
systemctl restart kubelet.service
```
但是pod的驱离时间通过node-monitor-period、node-monitor-grace-period、pod-eviction-timeout三个的配置没有起作用。
![image](https://user-images.githubusercontent.com/35677454/67547081-a4fc4d80-f730-11e9-925d-820ac43adeb5.png)
可以看到已经更新了启动配置，但是pod的驱离时间还是没变，通过 kubectl describe pod查看得到如下结果
![image](https://user-images.githubusercontent.com/35677454/67547264-2ce25780-f731-11e9-93ea-0d2ce256c96e.png)

所以我目前的做法是在deployment中添加如下配置：
```
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 5
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 5
      containers:
```
另可以参考[文章](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/kubernetes-reliability.md)，希望能够对你有帮助。
