### ISSUE TITLE
【已解决，建议修复】从v1.14.6升级到v.1.16.2遇到kubelet无法启动的问题，/var/lib/kubelet/config.yaml解析失败

### ISSUE THREAD

**Issue by Delacroix** [easzlab/kubeasz#730]
【现象】升级后发现该报错，发现是roles/kube-node/default/main.yml中所定义的资源预留格式与v1beta1.KubeletConfiguration.KubeReserved所要求的字典格式不匹配：
![图片](https://user-images.githubusercontent.com/1725134/68683184-53154d80-05a1-11ea-95b2-7fba008f6410.png)

【验证】尝试修改其中一个节点的配置后，可以启动kubelet：
![图片](https://user-images.githubusercontent.com/1725134/68683479-cf0f9580-05a1-11ea-948c-19acc9f51b71.png)

【临时解决方案】目前是手动将kubelet-config.yaml.j2中的资源预留写死来解决的，类似以下格式：
```
kubeReserved: 
  cpu: 200m
  memory: 500Mi
  ephemeral-storage: 1Gi
```
修改后重新upgrade，所有节点顺利升级并为Ready状态
