### ISSUE TITLE
如果etcd和master节点部署在一起，删除etcd的话会把/opt/kube/bin/下的二进制文件全部删除 导致master节点 无法启动

### ISSUE THREAD

**Issue by ilanni2460** [easzlab/kubeasz#837]
如果etcd和master节点部署在一起，删除etcd的话会把/opt/kube/bin/下的二进制文件全部删除 导致master节点 无法启动

需要修改
https://github.com/easzlab/kubeasz/blob/master/roles/clean/tasks/main.yml

第30行需要增加对删除bin目录下的文件进行判断

**Comment by gjmzj** [comment]
```
- name: remove binaries and offline images
  file: name={{ item }} state=absent
  with_items:
  - "/opt/kube/bin"
  - "/opt/kube/images"
  when: 'DEL_ETCD == "yes" and DEL_NODE == "yes" and DEL_MASTER == "yes"'
```
增加了判断条件，但是不太明白，你是怎么删除etcd的，按照tools/easzctl del-etcd 操作并不会调用这段代码，能不能写下复现步骤
