### ISSUE TITLE
prometheus 监控 显示 context deadline exceeded错误

### ISSUE THREAD

**Issue by legolas-zeng** [easzlab/kubeasz#840]
你好，我使用kubeasz安装的k8s集群，然后用二进制跑了prometheus监控，在监控pod服务的时候，我是这样配置的:
`prometheus.yml`:

``` 
 - job_name: 'kubernetes-service-endpoints'
    scheme: https
    kubernetes_sd_configs:
      - role: endpoints
        api_server: https://192.168.3.17:6443/
        tls_config:
          insecure_skip_verify: true
        bearer_token: "**************"
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
      action: replace
      target_label: __scheme__
      regex: (https?)
    - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
      action: replace
      target_label: __address__
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
    - action: labelmap
      regex: __meta_kubernetes_service_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_service_name]
      action: replace
      target_label: kubernetes_name
    - source_labels: [__meta_kubernetes_pod_node_name]
      action: replace
      target_label: kubernetes_node
```
pod服务是一个简单的nginx服务，配置如下`pod_server.yaml`:
```
apiVersion: v1
kind: Service
metadata:
  name: rrjc-algorithm
  namespace: default
  annotations:                      
    prometheus.io/scrape: 'true'    # 开启K8s动态监测后端pod数据
    prometheus.io/path: '/metrics'  #pod暴露的/metrics接口地址
    prometheus.io/port: '9163'      #pod暴露的采集数据端口
spec:
  selector:
    app: rrjc-algorithm
    release: canary
  ports:
  - name: http
    port: 8081
    targetPort: 80
    nodePort: 30001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: algorithm-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rrjc-algorithm
      release: canary
  template:
    metadata:
      labels:
        app: rrjc-algorithm
        release: canary
    spec:
      containers:
      - name: rrjc-algorithm
        image: ********.com/rrjc/httpd
        ports:
        - name: httpd
          containerPort: 80
      imagePullSecrets:        #使用的secret
      - name: registry-secret
```
pod服务能通过nodeport端口正常访问，但是prometheus监控中就显示：
`Get "https://172.20.107.216:9163/metrics": context deadline exceeded`错误。
![image](https://user-images.githubusercontent.com/27952739/81667337-b8c19400-9475-11ea-9851-4621e6ff5446.png)
求大佬们指教，多谢啦。
